language: c
sudo: false
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
install:
  - arduino --install-library "Adafruit CC3000 Library"
  - arduino --install-library "DHT sensor library"
script:
  - arduino --verify --board arduino:avr:uno $PWD/sensors_test/sensors_test.ino
notifications:
  email:
    on_success: change
    on_failure: change