language: c
sudo: false
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
install:
  - arduino --install-library "Adafruit CC3000 Library"
  - arduino --install-library "DHT sensor library"
  - arduino --install-library "Adafruit BMP085 Unified"
  - arduino --install-library "Adafruit Unified Sensor"
script:
  - build_platform uno
notifications:
  email:
    on_success: change
    on_failure: change
